create firs example
mpodanev/lm-screenshoter pull request #1
Opened 2020-05-28 08:35 UTC by mpodanev

@dyaroman Please review

2020-05-28 09:47 UTC, dyaroman requested changes

2020-05-28 09:47 UTC, dyaroman commented on README.md
> +* `--test` -- creates a set of test screenshots and compares them with your reference screenshots. You can use short command `-t`.
```suggestion
* `--test` -- creates a set of test screenshots and compares them with your reference screenshots. You can use an alias `-t`.
```

2020-05-28 09:47 UTC, dyaroman commented on README.md
> +  test screenshots. You can use a short command `-a`.
```suggestion
  test screenshots. You can use an alias `-a`.
```

2020-05-28 09:47 UTC, dyaroman commented on README.md
> +* `--project` -- set `project-name` to specify the project folder you'd like to test. You can use a short command `-p
```suggestion
* `--project` -- set `project-name` to specify the project folder you'd like to test. You can use an alias `-p
```

2020-05-28 09:47 UTC, dyaroman commented on README.md
> +###Examples
```suggestion
##Examples
```

2020-05-28 09:47 UTC, dyaroman commented on README.md
> +First of all, should install packages `npm ci` and `backstop init`.
Please read how to run local version of package without global instalation.

2020-05-28 09:47 UTC, dyaroman commented on index.js
> +const localhost = 'https://localhost:' + JSON.parse(fs.readFileSync(`${projectPath}${path.sep}${projectName}${path.sep}Properties${path.sep}launchSettings.json`, 'utf8'))
Please split this variable to several for more readability.

2020-05-28 09:47 UTC, dyaroman commented on index.js
> +    "project": projectName,
Please use single quote instead of double.

2020-05-29 10:11 UTC, mpodanev commented on README.md
> +First of all, should install packages `npm ci` and `backstop init`.
Добавил. Из node_modules можно запускать

2020-05-29 10:12 UTC, mpodanev commented
@dyaroman Добавил коммиты, посмотри, прими и давай обсудим че дальше делать. Может через Issues попробовать добавлять задачи

2020-05-29 10:25 UTC, dyaroman approved these changes
1. кавычки так и не привел к одному стилю
2. переменную "порт" не разделил

2020-05-29 10:30 UTC, mpodanev commented
> кавычки так и не привел к одному стилю

Та шо за рагуль 😞, сделаю

> переменную "порт" не разделил

Я разделили переменную `localhost` на `port` и `localhostUrl`.
Ты предлагаешь еще `port` дополнительно разделить?

2020-05-29 10:33 UTC, merged

2020-05-29 10:50 UTC, mpodanev commented
Так я же хотел поправить все что бы ты потом уже смерджил.
Я еще написал выше что сделаю